require("dotenv").config();
const { parseEnv } = require("./env.schema");

const env = parseEnv();

module.exports = {
  port: env.PORT,
  database: {
    host: env.DB_HOST,
    user: env.DB_USER,
    password: env.DB_PASSWORD,
    name: env.DB_NAME,
    port: env.DB_PORT,
  },
  jwtSecretKey: env.SECURITY_TOKEN_SECRET,
  AUTH_TOKEN_LIFE: env.SECURITY_TOKEN_LIFE,
  AUTH_TOKEN_SECRET: env.SECURITY_TOKEN_SECRET,
  OPENAI_API_KEY: env.OPENAI_API_KEY,
  OPENROUTER_API_KEY: env.OPENROUTER_API_KEY,
  OPENROUTER_BASE_URL: env.OPENROUTER_BASE_URL,
  OLLAMA_BASE_URL: env.OLLAMA_BASE_URL,
  ENVIRONMENT: env.ENVIRONMENT,
  CORS_ORIGINS: env.CORS_ORIGINS,
  LANGFUSE_SECRET_KEY: env.LANGFUSE_SECRET_KEY,
  LANGFUSE_PUBLIC_KEY: env.LANGFUSE_PUBLIC_KEY,
  LANGFUSE_BASE_URL: env.LANGFUSE_BASE_URL,
  LANGFUSE_TRACING_ENVIRONMENT: env.LANGFUSE_TRACING_ENVIRONMENT,
};
