#!/usr/bin/env bash
set -euo pipefail

LAN_IP="${1:-192.168.0.100}"
ENV_FILE="$(dirname "$0")/.env"

if [[ -f "$ENV_FILE" ]]; then
  echo "Backing up existing .env → .env.bak"
  cp "$ENV_FILE" "$ENV_FILE.bak"
fi

NEXTAUTH_SECRET="$(openssl rand -base64 32)"
ENCRYPTION_KEY="$(openssl rand -hex 32)"
SALT="$(openssl rand -base64 32)"

cat > "$ENV_FILE" <<EOF
# Generated by setup.sh — re-run to rotate secrets (wipes Langfuse encrypted data)
NEXTAUTH_URL=http://${LAN_IP}:3000
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
SALT=${SALT}
POSTGRES_PASSWORD=postgres
CLICKHOUSE_PASSWORD=clickhouse
REDIS_AUTH=myredissecret
MINIO_ROOT_PASSWORD=miniosecret
TELEMETRY_ENABLED=false
EOF

echo "Created ${ENV_FILE}"
echo "NEXTAUTH_URL=http://${LAN_IP}:3000"
echo ""
echo "Next steps:"
echo "  docker compose down"
echo "  docker compose up -d"
echo "  docker compose logs -f langfuse-web"
echo ""
echo "Then open http://${LAN_IP}:3000"
